# ---
# - name: Installing tradeoffer
#   hosts: tradeoffer_vagrant
#   pre_tasks:
#     - name: Install Docker
#       become: true
#       tags:
#       - docker
#       block:
#       - name: Adding Docker APT Registry
#         ansible.builtin.shell:
#           cmd: |
#             # Add Docker's official GPG key:
#             sudo apt-get -y update
#             sudo apt-get -y install ca-certificates curl
#             sudo install -m 0755 -d /etc/apt/keyrings
#             sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o/etc/apt/keyrings/docker.asc
#             sudo chmod a+r /etc/apt/keyrings/docker.asc
#             # Add the repository to Apt sources:
#             echo \
#               "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#               $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#               sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#               sudo apt-get -y update
#           creates: /etc/apt/keyrings/docker.asc
#       - name: Install Docker
#         ansible.builtin.apt:
#           name:
#             - docker-ce
#             - docker-ce-cli
#             - containerd.io
#             - docker-buildx-plugin
#             - docker-compose-plugin
#           state: present
#           update_cache: true
#   tasks:
#     - name: Tradeoffer installing
#       become: true
#       tags:
#         - tradeoffer
#       block:
#       - name: Run Tradeoffer role
#         ansible.builtin.import_role:
#           name: tradeoffer
---
- name: Installing tradeoffer
  hosts: all

  pre_tasks:
    - name: Install Docker
      become: true
      tags:
        - docker
      block:
        - name: Check Docker installation
          ansible.builtin.shell: command -v docker
          register: docker_installed
          ignore_errors: true

        - name: Install Docker
          ansible.builtin.shell: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            rm get-docker.sh
          when: docker_installed.rc != 0

  tasks:
    - name: Tradeoffer installing
      become: true
      tags:
        - tradeoffer
      block:
        - name: Run Tradeoffer role
          ansible.builtin.import_role:
            name: tradeoffer

    - name: Configure NGINX + TLS
      become: true
      tags:
        - nginx
      block:
        - name: Run NGINX role
          ansible.builtin.import_role:
            name: nginx
